### ISSUE TITLE
Create Initialize Dao Functions

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy-sdk#11]
There's a lot to this, which is 

Current implementations exist:
- https://github.com/metaDAOproject/futarchy/blob/develop/scripts/initializeDao.ts
- https://github.com/metaDAOproject/futarchy/blob/fbb160788c1a0df54c05de164fc9ab8046026595/scripts/main.ts#L302

Some implementation details:
- Different program versions require different args and accounts (contact R-K-H or Proph3t for details)
- We want to decouple from the use of META

**Comment by swaggymarie** [comment]
@R-K-H we might put that in backlog

**Comment by R-K-H** [comment]
Done

**Comment by R-K-H** [comment]
I appended week 10 just so we can carry along all the pending backlog tasks. And then when this stuff calms down some more we'll decide what we need to do with everything.
