### ISSUE TITLE
Review IDL Support System

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy-sdk#17]
There may be something to resolving previous versions and their IDLs (which may or may not speak to the usefulness of a mono-repo). Where you take the tag and fetch it from github when building, so we're not trying to store this stuff within the repo.

**Comment by Dodecahedr0x** [comment]
I like that there are all IDLs available in a single place somewhere but I agree that there is something wrong with the way it's done now. Maybe the solution is something like making the SDK tree-shaking compatible and let SDK users define what versions of the program they want so that their JS bundler only packages the useful IDLs?

**Comment by R-K-H** [comment]
> I like that there are all IDLs available in a single place somewhere but I agree that there is something wrong with the way it's done now. Maybe the solution is something like making the SDK tree-shaking compatible and let SDK users define what versions of the program they want so that their JS bundler only packages the useful IDLs?

I wish I had a simple answer. I don't honestly know. I mean of course other programs are upgradeable so their programs are always respecting the latest IDL...

The issue I have and this is what is the primary concern I want to address in OUR use of the SDK...

**We need to provide backwards compatibility to markets unless we've confirmed there are 0 deposits existing in conditional vaults.**

Users funds need to be accessible at least through our UI for the time being. And if we choose to no longer support, we need to announce and indicate as such. So I just was bringing up a concern, not that I have an ideal solution. The fact that we have program tagged versions is great, but we still have a lot to deal with and potentially moving forward so perhaps its a good time to think on a solution. Or at least make this solution more easily reasoned about.

**Comment by R-K-H** [comment]
I'm closing this for now given the solution implemented covers the requirement for now. But will remember it if needed.
