### ISSUE TITLE
Indexer implementation of FutarchyClient interface

### ISSUE THREAD

**Issue by decartesol** [metaDAOproject/futarchy-sdk#22]
Implement this interface https://github.com/metaDAOproject/futarchy-ts/blob/main/lib/client/client.ts
such that it gets data from indexer. Also, does the interface need extra methods for orderbook and trade history?

I recommend extension of the RPC API implementation

**Comment by LukasDeco** [comment]
@R-K-H do we want to mark this as done since the frontend is currently using the indexer implementation in staging? It just uses a lot of RPC still underneath, but those should be new tasks I think.

**Comment by R-K-H** [comment]
Okay so yes, but let's stub out another ticket specifically addressing the remaining functions https://github.com/metaDAOproject/futarchy-sdk/issues/43 I've added this for now, but will review with ya'll to update it.
