### ISSUE TITLE
Make FutarchyClient return Observables

### ISSUE THREAD

**Issue by decartesol** [metaDAOproject/futarchy-sdk#23]
Currently the futarchy client interface has this structure

```
export interface FutarchyClient {
  daos: FutarchyDaoClient;
  proposals: FutarchyProposalsClient;
  balances: FutarchyBalancesClient;
}

export interface FutarchyDaoClient {
  fetchAllDaos(): Promise<DaoWithTokens[]>;
  fetchDao(daoAddress: string): Promise<DaoWithTokens | undefined>;
}

export interface FutarchyProposalsClient {
  fetchProposals(dao: DaoAccount): Promise<ProposalWithVaults[]>;
}

export interface FutarchyBalancesClient {
  fetchMainTokenWalletBalances(
    dao: DaoWithTokens,
    ownerWallet: PublicKey
  ): Promise<TokenWithBalance[]>;
}
```

it's essentially a one-time fetch of data. We want to convert these to giving data real-time as it changes.
For that we can use some kind of [Observable](https://rxjs.dev/guide/observable) type pattern

**Comment by R-K-H** [comment]
We'll need to address subscription based API vs RPC failover. Which is most likely a schema if no API is assigned or no response is received...

Will discuss this and move it forward.

**Comment by R-K-H** [comment]
This is partially in progress / has been done with a few pieces. I'll close this issue for now given the pattern exists and we just need to identify where we need to expand these as necessary.
